[esp32-s3-st7735]
board = esp32-s3-devkitc-1
board_build.partitions = custom_16mb.csv

build_src_filter = ${env.build_src_filter} +<../boards/esp32-s3-st7735>

build_flags =
    ${env.build_flags}
    -Iboards/esp32-s3-st7735
    -DUSB_as_HID=1

    -Os

    -DCORE_DEBUG_LEVEL=1
    -DREDRAW_DELAY=1
    -DALLOW_ALL_GPIO_FOR_IR_RF=1
    -DDISABLE_ALL_LIBRARY_WARNINGS

    ; Board Identification
    -DESP32_S3_ST7735
    -DDEVICE_NAME="esp32-s3-st7735"

    ; Hardware Input Type
    -DHAS_5_BUTTONS

    ; I2C
    -DGROVE_SDA=18
    -DGROVE_SCL=8

    ; IR LED PIN
    -DIR_TX_PINS='{("W5 IR Mod", GROVE_SDA), ("Grove W", GROVE_SCL), ("Grove Y", GROVE_SDA)}'
    -DIR_RX_PINS='{("W5 IR Mod", GROVE_SCL), ("Grove W", GROVE_SDA), ("Grove Y", GROVE_SCL)}'
    -DIR_TX_PIN=1
    -DIR_RX_PIN=2
    -DTXLED=48
    -DOLED_ON=HIGH
    -DOLED_OFF=LOW

    ; Radio Frequency
    -DRF_TX_PINS='{("W5 RF433T", GROVE_SDA), ("Grove W", GROVE_SCL), ("Grove Y", GROVE_SDA)}'
    -DRF_RX_PINS='{("W5 RF433R", GROVE_SCL), ("Grove W", GROVE_SCL), ("Grove Y", GROVE_SCL)}'

    ; SD Card
    -DSDCARD_CS=40
    -DSDCARD_SCK=5
    -DSDCARD_MISO=41
    -DSDCARD_MOSI=6

    ; Display
    -DUSER_SETUP_LOADED=1
    -DST7735_DRIVER
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DST7735_GREENTAB3
    -DTFT_RGB_ORDER=TFT_BGR
    -DSMOOTH_FONT=1
    -DTFT_CS=16
    -DTFT_DC=7
    -DTFT_RST=15
    -DTFT_MOSI=6
    -DTFT_SCLK=5
    -DTFT_MISO=41
    -DTFT_BL=4
    -DTFT_BACKLIGHT_ON=HIGH
    -DFB=2
    -DTFT_SPI_PORT=FSPI

    -DHAS_SCREEN=1
    -DROTATION=1
    -DMINBRIGHT=1

    -DHAS_BTN=1
    -DBTN_ALIAS='"Mid"'
    -DBTN_PIN=0
    -DBTN_ACT=LOW
