name: Build Automatico Branch 2

on:
  push:
    branches:
      - "2"
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests esptool intelhex platformio

      - name: Run Compile
        run: |
          if [ -d "bruce-firmware" ]; then
            cd bruce-firmware
          fi
          echo "Iniciando compilação..."
          platformio run -e esp32-s3-st7735 || platformio run -e esp32-s3-devkitc-1 || platformio run

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Firmware-BIN-Branch2
          path: |
            .pio/build/**/*.bin
            **/firmware.bin
          if-no-files-found: error
